services:
  frontend:
    # uncomment the following line if you want to run a local instance of MongoDB
    # depends_on:
    #   - db
    build:
      context: .
      dockerfile: Dockerfile

    # do port mapping so that we can access the app from the browser
    ports:
      - 3000:3000

    # use docker compose to watch for changes and rebuild the container
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./next.config.js
          action: rebuild
        - path: ./yarn.lock
          action: rebuild
        - path: .
          target: /app
          action: sync

volumes:
  tasked:
